name: CI  on macos linux windows

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master

    - name: Build with ubuntu
      run: |
           JAVA_HOME=$JAVA_HOME_11_X64
           env
           mvn -f gson install -DskipTests=true
           mvn -f gson test   
                  
  windows:
   runs-on: windows-latest
   
   steps:
     - uses: actions/checkout@master
       
     - name: Build with windows  
       run: |
           set JAVA_HOME=$JAVA_HOME_11_X64
           echo $PATH
           mvn -f gson install -DskipTests=true
           mvn -f gson test   
                
  macos:
    runs-on: macos-latest
    
    steps:
     - uses: actions/checkout@master
       
     - name: Build with macos  
       run: |
           JAVA_HOME=$JAVA_HOME_11_X64
           env
           mvn -f gson install -DskipTests=true
           mvn -f gson test
