name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Build with Maven
      run: |
           JAVA_HOME=$JAVA_HOME_11_X64
           env
           mvn -f gson install -DskipTests=true
           mvn -f gson test
